name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/md-summarizer
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        envkey_MODEL: "gpt-3.5-turbo"
        envkey_PROVIDER: "openai"
        envkey_LOG_LEVEL: "WARNING"
        file_name: .env
        fail_on_empty: true

    - name: Run tests
      run: |
        pip install -e ".[test]"
        pytest -v

    - name: Build package
      run: python -m build

    - name: Publish package distributions to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*